"""Scriptwriter service: article -> subtitles.json using Claude Agent SDK."""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

from claude_code_sdk import ClaudeCodeOptions, query

from remotion_sub.config import settings

logger = logging.getLogger(__name__)

SCRIPTWRITER_SYSTEM_PROMPT = """你是一位拥有10年以上经验的精英短视频内容编导，专门为知识频道创建引人入胜的讲解视频脚本。

**核心原则：口播稿/解说词要极致精简，极致压缩。传递核心观点和关键论据即可。短视频才便于传播。**

## 你的任务

将用户提供的文章转换为短视频字幕脚本（subtitles.json），需要：
1. 提取核心信息和关键要点（3-5个主要观点）
2. 使用对话式第二人称语言
3. 保持句子简短（每句15-25个字）
4. 消除书面语习惯

## 视频结构

1. **开头吸引点**: 3-5秒的注意力抓取器，使用好奇心缺口、震惊事实、可共鸣的痛点或大胆陈述
2. **核心论点**: 2-4个关键点，每个有支撑证据或案例
3. **过渡衔接**: 段落之间的流畅连接
4. **结尾CTA**: 为观众提供清晰的下一步行动

## 输出要求

直接生成 subtitles.json 文件，JSON 结构如下：
```json
[
    {
        "scene": 1,
        "name": "镜头一：开头吸引点",
        "annotation": "[标注语气：疑问→反转]",
        "description": "画面描述，务必完整，后续将基于description生成分镜的画面",
        "subtitles": [
            {
                "file": "scene1-seg1.mp3",
                "text": "字幕文本",
                "rate": "+40%",
                "pitch": "+0Hz"
            }
        ]
    }
]
```

## 规范

- 每个 scene 的 subtitles 数组长度不超过 4 个
- 可以通过增加镜头数量来丰富内容表达
- 中文和英文之间有半角空格
- 中文和数字之间有半角空格
- 标点符号统一采用全角字符
- 每行字幕必须是完整的语义单元，不要把一句完整的话拆成多行
- text 既是字幕也是 TTS 文本，每条不超过 25 个汉字
- description 必须与 subtitles 文本保持一致性
- rate 默认 "+40%"，pitch 默认 "+0Hz"
- 文件命名：scene{场景编号}-seg{片段编号}.mp3
- 如果有 "——"，务必改成 "："

## 禁止
- 书面语词汇（鉴于、综上所述、本文）
- 长难句（超过25字必须拆分）
- 模糊的CTA（如：希望对你有帮助）
- 将完整句子拆成多行字幕
- JSON 中使用半角标点（逗号、句号等必须全角）
- 中英文、中文数字之间没有空格
"""


async def generate_script(
    session_dir: Path,
    article: str,
    requirements: str = "",
    on_progress=None,
) -> list[dict]:
    """Generate subtitles.json from article text using Claude Agent SDK.

    Returns the parsed JSON data.
    """
    prompt_parts = [
        "请将以下文章转换为短视频字幕脚本。",
        "直接在当前目录生成 subtitles.json 文件。",
        "确保生成的 JSON 格式正确，可以用 python3 -c \"import json; json.load(open('subtitles.json'))\" 验证。",
    ]
    if requirements:
        prompt_parts.append(f"\n用户的具体要求：\n{requirements}")
    prompt_parts.append(f"\n文章内容：\n{article}")

    prompt = "\n".join(prompt_parts)

    env = _build_env()

    async for msg in query(
        prompt=prompt,
        options=ClaudeCodeOptions(
            model=settings.claude_code_model,
            cwd=str(session_dir),
            system_prompt=SCRIPTWRITER_SYSTEM_PROMPT,
            allowed_tools=["Write", "Edit", "Read", "Bash"],
            max_turns=15,
            env=env,
        ),
    ):
        if on_progress and hasattr(msg, "content"):
            text = ""
            for block in (msg.content if isinstance(msg.content, list) else []):
                if hasattr(block, "text"):
                    text = block.text
                    break
            if text.strip():
                await on_progress(text[:200])
        logger.debug("scriptwriter msg: %s", getattr(msg, "type", "unknown"))

    # Read the generated file
    subtitles_path = session_dir / "subtitles.json"
    if not subtitles_path.exists():
        raise RuntimeError("subtitles.json was not generated by the scriptwriter agent")

    with open(subtitles_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list) or len(data) == 0:
        raise RuntimeError("subtitles.json is empty or not a list")

    logger.info("Generated %d scenes in subtitles.json", len(data))
    return data


def _build_env() -> dict[str, str]:
    env = os.environ.copy()
    env["ANTHROPIC_API_KEY"] = settings.openrouter_api_key
    env["ANTHROPIC_BASE_URL"] = "https://openrouter.ai/api/v1"
    return env
